// Mock data for YouthForge platform

export const mockProjects = [
  {
    id: '1',
    title: 'AI-Powered Study Assistant',
    description: 'A machine learning application that helps students with personalized study plans and adaptive learning paths.',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f70504ab5?w=500&h=300&fit=crop',
    category: 'AI/ML',
    tags: ['Python', 'TensorFlow', 'React', 'API'],
    author: 'Sarah Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    stars: 342,
    forks: 89,
    views: 2340,
    status: 'Active',
  },
  {
    id: '2',
    title: 'Web Design Portfolio Generator',
    description: 'Automated tool to generate professional portfolio websites from simple project descriptions.',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    category: 'Web Dev',
    tags: ['Next.js', 'Tailwind', 'Design', 'Automation'],
    author: 'Marcus Johnson',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    stars: 267,
    forks: 45,
    views: 1890,
    status: 'Active',
  },
  {
    id: '3',
    title: 'Mobile Health Tracker',
    description: 'Cross-platform mobile application for tracking fitness, nutrition, and mental wellness.',
    image: 'https://images.unsplash.com/photo-1512941691920-25bda36dc643?w=500&h=300&fit=crop',
    category: 'Mobile',
    tags: ['Flutter', 'Firebase', 'Health', 'Analytics'],
    author: 'Priya Patel',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    stars: 521,
    forks: 156,
    views: 3450,
    status: 'Active',
  },
  {
    id: '4',
    title: 'Real-time Collaboration Editor',
    description: 'Like Google Docs but with advanced features for developers and technical documentation.',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    category: 'Web Dev',
    tags: ['React', 'WebSockets', 'Collaborative', 'Real-time'],
    author: 'Alex Kumar',
    authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
    stars: 456,
    forks: 123,
    views: 2789,
    status: 'Active',
  },
  {
    id: '5',
    title: 'Blockchain NFT Marketplace',
    description: 'Decentralized platform for creating, buying, and selling digital art and collectibles.',
    image: 'https://images.unsplash.com/photo-1563986768609-2f77601d3f3f?w=500&h=300&fit=crop',
    category: 'Blockchain',
    tags: ['Web3', 'Solidity', 'NFT', 'Ethereum'],
    author: 'Jordan White',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    stars: 634,
    forks: 201,
    views: 4123,
    status: 'Active',
  },
  {
    id: '6',
    title: 'Eco-Tracking IoT System',
    description: 'Smart sensors and dashboard for monitoring environmental data and carbon footprint.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=300&fit=crop',
    category: 'IoT',
    tags: ['IoT', 'Arduino', 'Python', 'Dashboard'],
    author: 'Emma Green',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    stars: 298,
    forks: 67,
    views: 1567,
    status: 'Active',
  },
];

export const mockDevelopers = [
  {
    id: '1',
    name: 'Sarah Chen',
    title: 'Full Stack Developer & AI Enthusiast',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    skills: ['React', 'Python', 'TensorFlow', 'Node.js', 'PostgreSQL'],
    bio: 'Passionate about building intelligent systems and sharing knowledge with the community.',
    location: 'San Francisco, CA',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    projects: 24,
    followers: 1240,
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    title: 'UI/UX Designer & Frontend Dev',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    skills: ['React', 'Figma', 'Tailwind CSS', 'Next.js', 'Design Systems'],
    bio: 'Creating beautiful, accessible, and performant web experiences.',
    location: 'Brooklyn, NY',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    projects: 18,
    followers: 892,
  },
  {
    id: '3',
    name: 'Priya Patel',
    title: 'Mobile Developer & DevOps Engineer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    skills: ['Flutter', 'Dart', 'Docker', 'AWS', 'Firebase'],
    bio: 'Specialized in cross-platform mobile apps and cloud infrastructure.',
    location: 'Toronto, Canada',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    projects: 32,
    followers: 1567,
  },
  {
    id: '4',
    name: 'Alex Kumar',
    title: 'Backend Engineer & System Architect',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
    skills: ['Go', 'Rust', 'Microservices', 'Kubernetes', 'gRPC'],
    bio: 'Building scalable and robust backend systems for millions of users.',
    location: 'Bangalore, India',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    projects: 28,
    followers: 2103,
  },
  {
    id: '5',
    name: 'Jordan White',
    title: 'Web3 Developer & Smart Contract Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    skills: ['Solidity', 'Web3.js', 'Ethereum', 'React', 'OpenZeppelin'],
    bio: 'Pioneering the future of decentralized applications.',
    location: 'Austin, TX',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    projects: 15,
    followers: 987,
  },
  {
    id: '6',
    name: 'Emma Green',
    title: 'IoT Specialist & Hardware Engineer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    skills: ['Arduino', 'Python', 'IoT Protocols', 'C++', 'PCB Design'],
    bio: 'Connecting the physical and digital worlds through IoT solutions.',
    location: 'Portland, OR',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    projects: 22,
    followers: 765,
  },
];

export const mockChallenges = [
  {
    id: '1',
    title: 'Build a Carbon Footprint Calculator',
    description: 'Create an application that helps users calculate and understand their personal carbon footprint.',
    difficulty: 'Intermediate',
    category: 'Sustainability',
    image: 'https://images.unsplash.com/photo-1518633150987-15edac482f3d?w=500&h=300&fit=crop',
    tags: ['Python', 'Web Dev', 'Data Analysis'],
    prize: '$500',
    participants: 234,
    deadline: '2024-12-15',
  },
  {
    id: '2',
    title: 'Design a Chatbot for Mental Health Support',
    description: 'Develop an AI-powered chatbot that provides supportive conversations and mental health resources.',
    difficulty: 'Hard',
    category: 'AI/Wellness',
    image: 'https://images.unsplash.com/photo-1515378791036-0648a3fb7cf0?w=500&h=300&fit=crop',
    tags: ['NLP', 'AI', 'Python', 'React'],
    prize: '$1000',
    participants: 156,
    deadline: '2024-12-20',
  },
  {
    id: '3',
    title: 'Create a Gamified Learning Platform',
    description: 'Build an educational platform with gamification elements to boost student engagement.',
    difficulty: 'Hard',
    category: 'EdTech',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    tags: ['React', 'Game Dev', 'Educational'],
    prize: '$1500',
    participants: 189,
    deadline: '2025-01-10',
  },
  {
    id: '4',
    title: 'Build a Privacy-First Weather App',
    description: 'Create a weather application that respects user privacy with no tracking or data collection.',
    difficulty: 'Easy',
    category: 'Mobile',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
    tags: ['Flutter', 'Mobile', 'Privacy'],
    prize: '$300',
    participants: 412,
    deadline: '2024-11-30',
  },
  {
    id: '5',
    title: 'Design Accessible Web Components',
    description: 'Create a library of reusable web components that prioritize accessibility and WCAG compliance.',
    difficulty: 'Intermediate',
    category: 'Web Dev',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    tags: ['Web Components', 'Accessibility', 'React'],
    prize: '$800',
    participants: 267,
    deadline: '2025-01-15',
  },
  {
    id: '6',
    title: 'Develop a Real-Time Collaboration Tool',
    description: 'Build a tool that allows multiple users to collaborate in real-time on documents or projects.',
    difficulty: 'Hard',
    category: 'Collaboration',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    tags: ['WebSockets', 'React', 'Real-time', 'Backend'],
    prize: '$2000',
    participants: 145,
    deadline: '2025-01-30',
  },
];

export const mockUser = {
  id: 'user-1',
  name: 'Alex Thompson',
  title: 'Full Stack Developer & Open Source Enthusiast',
  avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
  cover: 'https://images.unsplash.com/photo-1557821552-17105176677c?w=1200&h=400&fit=crop',
  bio: 'Building amazing things with code. Coffee addict. Always learning.',
  location: 'San Francisco, CA',
  joinedDate: 'January 2023',
  github: 'https://github.com',
  linkedin: 'https://linkedin.com',
  twitter: 'https://twitter.com',
  website: 'https://alexthompson.dev',
  stats: {
    projects: 24,
    followers: 1240,
    following: 345,
    contributions: 5678,
  },
  skills: ['React', 'Node.js', 'TypeScript', 'Python', 'PostgreSQL', 'Docker', 'AWS'],
  projects: [
    { id: '1', title: 'AI-Powered Study Assistant', description: 'ML-based learning platform', image: 'https://images.unsplash.com/photo-1516321318423-f06f70504ab5?w=500&h=300&fit=crop' },
    { id: '2', title: 'Web Design Portfolio Generator', description: 'Automated portfolio creation tool', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop' },
    { id: '3', title: 'Real-time Collaboration Editor', description: 'Multiplayer document editor', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop' },
  ],
};

export const categories = ['All', 'Web Dev', 'Mobile', 'AI/ML', 'Blockchain', 'IoT', 'Design'];
export const skillTags = ['React', 'Node.js', 'Python', 'TypeScript', 'Vue', 'Angular', 'Django', 'FastAPI', 'Flutter', 'Swift'];
export const challengeCategories = ['All', 'AI/Wellness', 'EdTech', 'Mobile', 'Web Dev', 'Sustainability', 'Collaboration', 'Design'];
